/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as LogRouteImport } from './routes/log'
import { Route as MapRouteImport } from './routes/map'
import { Route as MoreRouteImport } from './routes/more'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as WrapRouteImport } from './routes/wrap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WrapRoute = WrapRouteImport.update({
  id: '/wrap',
  path: '/wrap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/interviews': typeof InterviewsRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/more': typeof MoreRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/wrap': typeof WrapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/interviews': typeof InterviewsRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/more': typeof MoreRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/wrap': typeof WrapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/interviews': typeof InterviewsRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/more': typeof MoreRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/wrap': typeof WrapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/interviews'
    | '/log'
    | '/map'
    | '/more'
    | '/notes'
    | '/settings'
    | '/timeline'
    | '/wrap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/interviews'
    | '/log'
    | '/map'
    | '/more'
    | '/notes'
    | '/settings'
    | '/timeline'
    | '/wrap'
  id:
    | '__root__'
    | '/'
    | '/interviews'
    | '/log'
    | '/map'
    | '/more'
    | '/notes'
    | '/settings'
    | '/timeline'
    | '/wrap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InterviewsRoute: typeof InterviewsRoute
  LogRoute: typeof LogRoute
  MapRoute: typeof MapRoute
  MoreRoute: typeof MoreRoute
  NotesRoute: typeof NotesRoute
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
  WrapRoute: typeof WrapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrap': {
      id: '/wrap'
      path: '/wrap'
      fullPath: '/wrap'
      preLoaderRoute: typeof WrapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InterviewsRoute: InterviewsRoute,
  LogRoute: LogRoute,
  MapRoute: MapRoute,
  MoreRoute: MoreRoute,
  NotesRoute: NotesRoute,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
  WrapRoute: WrapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
