/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EventRouteImport } from './routes/event'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as LogRouteImport } from './routes/log'
import { Route as MapRouteImport } from './routes/map'
import { Route as MoreRouteImport } from './routes/more'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as WrapRouteImport } from './routes/wrap'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as EventIndexRouteImport } from './routes/event.index'
import { Route as EventCompetitionsRouteImport } from './routes/event.competitions'
import { Route as EventSpeakersRouteImport } from './routes/event.speakers'
import { Route as ReleasesIndexRouteImport } from './routes/releases.index'
import { Route as ReleasesAdultRouteImport } from './routes/releases.adult'
import { Route as ReleasesMinorRouteImport } from './routes/releases.minor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRoute = EventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WrapRoute = WrapRouteImport.update({
  id: '/wrap',
  path: '/wrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EventIndexRoute = EventIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventRoute,
} as any)
const EventCompetitionsRoute = EventCompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => EventRoute,
} as any)
const EventSpeakersRoute = EventSpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => EventRoute,
} as any)
const ReleasesIndexRoute = ReleasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReleasesRoute,
} as any)
const ReleasesAdultRoute = ReleasesAdultRouteImport.update({
  id: '/adult',
  path: '/adult',
  getParentRoute: () => ReleasesRoute,
} as any)
const ReleasesMinorRoute = ReleasesMinorRouteImport.update({
  id: '/minor',
  path: '/minor',
  getParentRoute: () => ReleasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/event': typeof EventRouteWithChildren
  '/interviews': typeof InterviewsRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/more': typeof MoreRoute
  '/notes': typeof NotesRoute
  '/releases': typeof ReleasesRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/wrap': typeof WrapRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/event/competitions': typeof EventCompetitionsRoute
  '/event/speakers': typeof EventSpeakersRoute
  '/releases/adult': typeof ReleasesAdultRoute
  '/releases/minor': typeof ReleasesMinorRoute
  '/event/': typeof EventIndexRoute
  '/releases/': typeof ReleasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/interviews': typeof InterviewsRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/more': typeof MoreRoute
  '/notes': typeof NotesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/wrap': typeof WrapRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/event/competitions': typeof EventCompetitionsRoute
  '/event/speakers': typeof EventSpeakersRoute
  '/releases/adult': typeof ReleasesAdultRoute
  '/releases/minor': typeof ReleasesMinorRoute
  '/event': typeof EventIndexRoute
  '/releases': typeof ReleasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/event': typeof EventRouteWithChildren
  '/interviews': typeof InterviewsRoute
  '/log': typeof LogRoute
  '/map': typeof MapRoute
  '/more': typeof MoreRoute
  '/notes': typeof NotesRoute
  '/releases': typeof ReleasesRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/wrap': typeof WrapRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/event/competitions': typeof EventCompetitionsRoute
  '/event/speakers': typeof EventSpeakersRoute
  '/releases/adult': typeof ReleasesAdultRoute
  '/releases/minor': typeof ReleasesMinorRoute
  '/event/': typeof EventIndexRoute
  '/releases/': typeof ReleasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/event'
    | '/interviews'
    | '/log'
    | '/map'
    | '/more'
    | '/notes'
    | '/releases'
    | '/search'
    | '/settings'
    | '/timeline'
    | '/wrap'
    | '/admin'
    | '/event/competitions'
    | '/event/speakers'
    | '/releases/adult'
    | '/releases/minor'
    | '/event/'
    | '/releases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/interviews'
    | '/log'
    | '/map'
    | '/more'
    | '/notes'
    | '/search'
    | '/settings'
    | '/timeline'
    | '/wrap'
    | '/admin'
    | '/event/competitions'
    | '/event/speakers'
    | '/releases/adult'
    | '/releases/minor'
    | '/event'
    | '/releases'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/event'
    | '/interviews'
    | '/log'
    | '/map'
    | '/more'
    | '/notes'
    | '/releases'
    | '/search'
    | '/settings'
    | '/timeline'
    | '/wrap'
    | '/_authenticated/admin'
    | '/event/competitions'
    | '/event/speakers'
    | '/releases/adult'
    | '/releases/minor'
    | '/event/'
    | '/releases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EventRoute: typeof EventRouteWithChildren
  InterviewsRoute: typeof InterviewsRoute
  LogRoute: typeof LogRoute
  MapRoute: typeof MapRoute
  MoreRoute: typeof MoreRoute
  NotesRoute: typeof NotesRoute
  ReleasesRoute: typeof ReleasesRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
  WrapRoute: typeof WrapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event': {
      id: '/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrap': {
      id: '/wrap'
      path: '/wrap'
      fullPath: '/wrap'
      preLoaderRoute: typeof WrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/event/': {
      id: '/event/'
      path: '/'
      fullPath: '/event/'
      preLoaderRoute: typeof EventIndexRouteImport
      parentRoute: typeof EventRoute
    }
    '/event/competitions': {
      id: '/event/competitions'
      path: '/competitions'
      fullPath: '/event/competitions'
      preLoaderRoute: typeof EventCompetitionsRouteImport
      parentRoute: typeof EventRoute
    }
    '/event/speakers': {
      id: '/event/speakers'
      path: '/speakers'
      fullPath: '/event/speakers'
      preLoaderRoute: typeof EventSpeakersRouteImport
      parentRoute: typeof EventRoute
    }
    '/releases/': {
      id: '/releases/'
      path: '/'
      fullPath: '/releases/'
      preLoaderRoute: typeof ReleasesIndexRouteImport
      parentRoute: typeof ReleasesRoute
    }
    '/releases/adult': {
      id: '/releases/adult'
      path: '/adult'
      fullPath: '/releases/adult'
      preLoaderRoute: typeof ReleasesAdultRouteImport
      parentRoute: typeof ReleasesRoute
    }
    '/releases/minor': {
      id: '/releases/minor'
      path: '/minor'
      fullPath: '/releases/minor'
      preLoaderRoute: typeof ReleasesMinorRouteImport
      parentRoute: typeof ReleasesRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EventRouteChildren {
  EventCompetitionsRoute: typeof EventCompetitionsRoute
  EventSpeakersRoute: typeof EventSpeakersRoute
  EventIndexRoute: typeof EventIndexRoute
}

const EventRouteChildren: EventRouteChildren = {
  EventCompetitionsRoute: EventCompetitionsRoute,
  EventSpeakersRoute: EventSpeakersRoute,
  EventIndexRoute: EventIndexRoute,
}

const EventRouteWithChildren = EventRoute._addFileChildren(EventRouteChildren)

interface ReleasesRouteChildren {
  ReleasesAdultRoute: typeof ReleasesAdultRoute
  ReleasesMinorRoute: typeof ReleasesMinorRoute
  ReleasesIndexRoute: typeof ReleasesIndexRoute
}

const ReleasesRouteChildren: ReleasesRouteChildren = {
  ReleasesAdultRoute: ReleasesAdultRoute,
  ReleasesMinorRoute: ReleasesMinorRoute,
  ReleasesIndexRoute: ReleasesIndexRoute,
}

const ReleasesRouteWithChildren = ReleasesRoute._addFileChildren(
  ReleasesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EventRoute: EventRouteWithChildren,
  InterviewsRoute: InterviewsRoute,
  LogRoute: LogRoute,
  MapRoute: MapRoute,
  MoreRoute: MoreRoute,
  NotesRoute: NotesRoute,
  ReleasesRoute: ReleasesRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
  WrapRoute: WrapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
