/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as LogRouteImport } from './routes/log'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as WrapRouteImport } from './routes/wrap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WrapRoute = WrapRouteImport.update({
  id: '/wrap',
  path: '/wrap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/interviews': typeof InterviewsRoute
  '/log': typeof LogRoute
  '/timeline': typeof TimelineRoute
  '/wrap': typeof WrapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/interviews': typeof InterviewsRoute
  '/log': typeof LogRoute
  '/timeline': typeof TimelineRoute
  '/wrap': typeof WrapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/interviews': typeof InterviewsRoute
  '/log': typeof LogRoute
  '/timeline': typeof TimelineRoute
  '/wrap': typeof WrapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/interviews' | '/log' | '/timeline' | '/wrap'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/interviews' | '/log' | '/timeline' | '/wrap'
  id: '__root__' | '/' | '/interviews' | '/log' | '/timeline' | '/wrap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InterviewsRoute: typeof InterviewsRoute
  LogRoute: typeof LogRoute
  TimelineRoute: typeof TimelineRoute
  WrapRoute: typeof WrapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrap': {
      id: '/wrap'
      path: '/wrap'
      fullPath: '/wrap'
      preLoaderRoute: typeof WrapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InterviewsRoute: InterviewsRoute,
  LogRoute: LogRoute,
  TimelineRoute: TimelineRoute,
  WrapRoute: WrapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
